[project]
name = "ac3-intro-to-jinja"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jinja2",
    "pyyaml",
    "httpx",
]
