# -*- coding: utf-8 -*-
"""ac3_intro_to_jinja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qrl9WZ9y3ryrrV3BnDP4w65MfOlBth3R

# AutoCon3 Introduction to jinja
"""

# pip install jinja2

"""jinja2 already available in colab environment"""

tmp_str = "I am in {{ city }}"

import jinja2 as j2

t = j2.Template(tmp_str)

result = t.render(city="Denver")

print(result)

mydict = {"city": "Los Angeles"}

result2 = t.render(mydict)

print(result2)

